### ISSUE TITLE
Hacer prueba de comandos GIT

### ISSUE THREAD

**Issue by EdwardTel** [EdwardTel/DevTic-Masters#6]
Para esta tarea es necesario que todos se instalen GIT. La interfaz es a traves de una terminal propia de GIT, pero los comandos se pueden usar desde cualquier terminal de las que ya usamos, bien sea la de Visual Studio Code, el cmd o powershell de windows, o la terminal bash de GIT.

En todo caso los comandos son los mismos. Comandos a revisar:

git --version
git clone
git branch
git checkout
git status
git add
git commit
git push
git pull
git revert
git merge

**Comment by NathaliaReyes** [comment]
Tarea de prueba
